<?php
function business_reviews_theme($existing, $type, $theme, $path) {
    $variables = array(
      'reviews_list' => array(
        'variables' => array(
          'reviews' => NULL,
          'parent' => NULL,
          'api_id' => NULL,
        ),
        'template' => 'block--reviews-list',
      ),
      'add_review' => array(
        'render element' => 'form'
       )
    );
    return $variables;
  }

function business_reviews_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  $form['#attached']['library'][] = 'business_reviews/form_stars';
  return $form;
}